// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: String.fromEnvironment('FIREBASE_APP_ID_WEB'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID_WEB'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: 'karteji-e367d'),
    authDomain: String.fromEnvironment('FIREBASE_AUTH_DOMAIN_WEB', defaultValue: 'karteji-e367d.firebaseapp.com'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET_WEB', defaultValue: 'karteji-e367d.firebasestorage.app'),
    measurementId: String.fromEnvironment('FIREBASE_MEASUREMENT_ID_WEB', defaultValue: 'G-4KNXCFGTE6'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'MOCK_API_KEY',
    appId: 'MOCK_APP_ID',
    messagingSenderId: 'MOCK_MESSAGING_SENDER_ID',
    projectId: 'karteji-e367d',
    storageBucket: 'karteji-e367d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'MOCK_API_KEY',
    appId: 'MOCK_APP_ID',
    messagingSenderId: 'MOCK_MESSAGING_SENDER_ID',
    projectId: 'karteji-e367d',
    storageBucket: 'karteji-e367d.firebasestorage.app',
    iosBundleId: 'com.karteji.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'MOCK_API_KEY',
    appId: 'MOCK_APP_ID',
    messagingSenderId: 'MOCK_MESSAGING_SENDER_ID',
    projectId: 'karteji-e367d',
    storageBucket: 'karteji-e367d.firebasestorage.app',
    iosBundleId: 'com.karteji.app',
  );
}
